
set(FILES
    Source/DualSenseModuleInterface.cpp
    Source/DualSenseModuleInterface.h
    Source/Clients/DualSenseSystemComponent.cpp
    Source/Clients/DualSenseSystemComponent.h
    Source/Clients/DualSenseSystemImpl.h
    Source/Clients/DualSenseGamepadButtonMap.h
    Source/Clients/DualSenseDebugGamepadImpl.cpp
    Source/Clients/DualSenseDebugGamepadImpl.h
    Source/Clients/DualSenseSlotTracker.h
    Source/Clients/DualSenseSlotTracker.cpp
    Source/Clients/DualSenseTriggerEffectMapping.cpp
    Source/Clients/DualSenseDs5Protocol.cpp
    Source/Clients/DualSenseTriggerFireDetector.h
    Source/Clients/DualSenseTriggerFireDetector.cpp
    Source/Clients/DualSenseSdlBackendProbe.h
    Source/Clients/DualSenseSdlBackendProbe.cpp
    Source/Clients/DualSenseBackendSelection.h
    Source/Clients/DualSenseBackendSelection.cpp
    Source/Clients/Sdl/DualSenseSdlAxisMath.h
    Source/Clients/Sdl/DualSenseSdlAxisMath.cpp
    Source/Clients/Sdl/DualSenseSdlRuntime.h
    Source/Clients/Sdl/DualSenseSdlRuntime.cpp
    Source/Clients/Sdl/DualSenseSdlMonitor.h
    Source/Clients/Sdl/DualSenseSdlMonitor.cpp
    Source/Clients/Sdl/InputDeviceGamepadDualSenseSdl.h
    Source/Clients/Sdl/InputDeviceGamepadDualSenseSdl.cpp
)
