
set(PAL_TRAIT_DUALSENSE_SUPPORTED FALSE)
set(PAL_TRAIT_DUALSENSE_TEST_SUPPORTED FALSE)
set(PAL_TRAIT_DUALSENSE_EDITOR_TEST_SUPPORTED FALSE)

# Phase 3a: no SDL3 fetch/link on this platform.
set(PAL_TRAIT_DUALSENSE_SDL_BACKEND FALSE)
